Upgrade to angular 4 and add functionalities from live version
stevermeister/dutch-tax-income-calculator2 pull request #6
Opened 2017-05-31 23:31 UTC by eduardomourar

This is related to pull request on version 1 of calculator [here](https://github.com/stevermeister/dutch-tax-income-calculator/pull/54). It adds functionalities as described below:
- Update to angular 4 (by creating a new project using angular-cli);
- Copy all the logic from the live version 1 of calculator;
- Proper calculation for holiday allowance (using special rate table);
- Some design improvements (but still requires more);
- Support to i18n (en, nl, pt, ru);
- Add unit test.

2017-06-01 07:58 UTC, stevermeister requested changes

2017-06-01 07:58 UTC, stevermeister commented on .vscode/launch.json
> +{
I think we can remove this file from repo

2017-06-01 07:58 UTC, stevermeister commented on src/app/app.component.ts
> +    translation.addLangs(['en', 'nl', 'pt', 'ru']);
👍

2017-06-01 07:58 UTC, stevermeister commented on src/app/calculate.service.spec.ts
> +      let stubCalc = [{
👍 👍 👍

2017-06-01 07:58 UTC, stevermeister commented on src/app/calculate.service.ts
> +@Injectable()
no need for @Injectable decorator here

2017-06-01 07:58 UTC, stevermeister commented on src/app/calculate.service.ts
> +    CalculateService._inputSubject.subscribe(input=> {
the first rule about Rxjs: if you subscribe inside service - you are doing something wrong

2017-06-01 07:58 UTC, stevermeister commented on src/app/calculate.service.ts
> +    CalculateService._inputSubject.next(value);
and one more thing about styling: I found code style when you put $ at the end of property name for Observables and $$ for Subjects pretty useful, for example:
    
    _outputResult$$.next(result)

2017-06-01 07:58 UTC, stevermeister commented on src/app/calculate.service.ts
> +  private newtonRaphson(f: any, x0: number, options: any): number {
I think this could go into separate service, because it's not related to salary calculations directly

2017-06-01 07:58 UTC, stevermeister commented on src/app/content.component.ts
> +  public rename(str: string): string {
maybe it's better to skip this magic?

2017-06-01 07:58 UTC, stevermeister commented on src/app/euro.pipe.ts
> +export class EuroPipe extends DecimalPipe implements PipeTransform {
why not to use just [CurrencyPipe](https://angular.io/docs/ts/latest/api/common/index/CurrencyPipe-pipe.html)?

2017-06-01 07:58 UTC, stevermeister commented on src/assets/i18n/ru.json
> +  "ADVANCED": "Дополнительные параметры",
I'll do native translations for it after.
and btw what is your native language?

2017-06-01 08:00 UTC, stevermeister commented
Thank you for your great contribution!
I made some remarks about the code.

Could you also please put screenshot of current design in PR description?

2017-06-01 09:18 UTC, eduardomourar commented on src/assets/i18n/ru.json
> +  "ADVANCED": "Дополнительные параметры",
mine is Brazilian Portuguese

2017-06-01 09:21 UTC, eduardomourar commented on src/app/calculate.service.ts
> +  private newtonRaphson(f: any, x0: number, options: any): number {
you are probably right. i just tried to keep it simple and with less files and folder as possible

2017-06-01 09:24 UTC, eduardomourar commented on .vscode/launch.json
> +{
better to add the .vscode to gitignore then

2017-06-01 09:41 UTC, eduardomourar commented on src/app/euro.pipe.ts
> +export class EuroPipe extends DecimalPipe implements PipeTransform {
at first i used currencypipe, but it doesn't allow me to customize much. in the end it was easiear to extend decimalpipe to add spaces and number sign

2017-06-01 09:47 UTC, eduardomourar commented on src/app/content.component.ts
> +  public rename(str: string): string {
this one is actually useful so we don't have to manually put on template each translation name in the format "TRANSLATION_TITLE"

2017-06-01 09:49 UTC, eduardomourar commented on src/app/calculate.service.ts
> +@Injectable()
yep, i will remove here and in the import

2017-06-01 09:49 UTC, eduardomourar commented on src/app/calculate.service.ts
> +    CalculateService._inputSubject.subscribe(input=> {
any suggestion on change?

2017-06-01 09:52 UTC, eduardomourar commented on src/app/calculate.service.ts
> +    CalculateService._inputSubject.next(value);
alright

2017-06-01 09:54 UTC, eduardomourar commented
i added screenshot to description. i might not have much time to work on all the changes right, but i will try my best to do it ASAP

2017-06-18 17:58 UTC, eduardomourar commented on package.json
> +    "build:prod": "ng build --prod --aot=false --base-href \"https://eduardomourar.github.io/dutch-tax-income-calculator2/\"",
make sure you to review this line and change it if you are deploying to github page.

2017-06-18 18:01 UTC, eduardomourar commented on src/app/app.component.html
> +        <a md-menu-item href="https://github.com/eduardomourar/dutch-tax-income-calculator2" mdTooltip="{{'GITHUB'|translate}}" mdTooltipPosition="right">
@stevermeister, change this from my repository to yours (also on line 32)

2017-07-01 15:11 UTC, stevermeister commented
👍 
I'll check the NL/RU translations and also will ask my friends to make professional design for it and we are ready to go live with V3!

2017-07-01 15:11 UTC, merged

2017-07-02 09:33 UTC, eduardomourar commented
Excellent! Let me know when it is live so I can test the deployed version.

2017-07-02 09:42 UTC, stevermeister commented
sure. 

Also I'm thinking about better SEO by having subroutes for each language like 
- http://thetax.nl/nl
- http://thetax.nl/en

what is your opinion about this?

2017-07-02 09:54 UTC, eduardomourar commented
I agree on creating subroutes, besides better CEO, it is a lot clear for the user as well.